global:
  smtp_require_tls: false

templates:
- '/etc/alertmanager/*.tmpl'
# The root route on which each incoming alert enters.
route:
  # default route if none match
  receiver: alert-emailer

  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  # TODO:
  group_by: ['alertname', 'priority']

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.

receivers:
- name: alert-emailer
  email_configs:
  - to: 'customer@example.com'
    send_resolved: false
    from: 'noreply@katzefudder.de'
    smarthost: 'mailhog:1025'
    auth_username: 'sender@example.com'
    #auth_password: 'IamPassword'
    #auth_secret: 'sender@example.com'
    #auth_identity: 'sender@example.com'